"""empty message

Revision ID: 6291d22cc0c7
Revises: e1c3796b24fc
Create Date: 2020-07-26 12:22:35.315464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6291d22cc0c7'
down_revision = 'e1c3796b24fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('d_legs', sa.Integer(), nullable=True),
    sa.Column('c_food', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
