"""empty message

Revision ID: 9d5e77b704c7
Revises: 6291d22cc0c7
Create Date: 2020-07-26 12:43:04.138733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5e77b704c7'
down_revision = '6291d22cc0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('c_food', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('d_legs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    op.drop_table('cat')
    # ### end Alembic commands ###
